apiVersion: v1
kind: Service
metadata:
  name: python-devops-service
spec:
  type: LoadBalancer
  selector:
    app: python-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
